### ISSUE TITLE
ブラウザで色変更(fishみたいな)

### ISSUE THREAD

**Issue by ctare** [non258/colter#64]
fishみたいにブラウザでぽちぽち色変更したいなと思いました

**Comment by non258** [comment]
とりあえずfishのソースを調査してみようと思います。

**Comment by non258** [comment]
_目標_

- ターミナルから自動でブラウザへ画面遷移すること
- 設定がlocalに反映されること(ブラウザから設定ができる)
- なるべくわかりやすいUI

**Comment by ctare** [comment]
わかりやすいUIってとこは、別issueに分けていいかも？
ひとまずはブラウザから操作できると嬉しさ溢れそう

**Comment by non258** [comment]
`config_brows_open` というbranchにとりあえずブラウザを立ち上げるところまで作ってみました。
`colter --config` でブラウザが立ち上がると思います。
現段階で非同期処理?ができていないのと、ブラウザを立ち上げたあとに立ち上げたターミナルにエラーが出るので、このあとどのように実装していくかアドバイスおねがいしたいです...

**Comment by non258** [comment]
npm iもおねがいします

**Comment by non258** [comment]
ブラウザからcolterの実行を行い設定を更新するところまで作成しました。
機能の拡張、ブラウザのUIは別途issueにて対応したいと思います。
PRは #71 がmergeされてから行いたいのでレビューをおねがいします。

**Comment by non258** [comment]
ブラウザから色の変更が可能になったのでこのissueはcloseします，
機能拡張や追加などは別途issueで対応しようと思います．
